# Please update /.travis/javas/.travis.yml in the cucumber/cucumber monorepo
# and sync:
#
#     source scripts/functions.sh && rsync_files
#
sudo: false
language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5373e574ed4e88026838
    on_success: change
    on_failure: always
    on_start: never
